# Generated by Django 2.1.1 on 2021-05-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentName', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=255, null=True)),
                ('Department', models.CharField(max_length=255, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('DateOfBirth', models.DateField(null=True)),
                ('Picture', models.FileField(blank=True, null=True, upload_to='employee/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='Manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.Employee'),
        ),
    ]
