#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. (Answer: 4613732) (solution code attached: problem_2_solution_code.py)



def FibonacciSequence(limit):
	SumFibonacciSequence = 0
	a=0
	b=1
	c=0
	while True:
		c = a+b
		if c %2 == 0:
			SumFibonacciSequence = SumFibonacciSequence + c
		a = b
		b = c
		if limit < c:
			print( SumFibonacciSequence)
			return  SumFibonacciSequence

func_call = FibonacciSequence(4000000)
print('Sum Fibonacci Sequence is',func_call )
